services:
  telegram-bot:
    build: .
    container_name: modular-telegram-bot
    restart: unless-stopped
    volumes:
      # 持久化配置
      - ./config:/app/config
      # ./logs:/app/logs
      # 如果需要热更新模块，取消下面的注释
      # - ./modules:/app/modules
    environment:
      - TZ=Asia/Hong_Kong
      # 可选：通过环境变量设置配置（优先级高于配置文件）
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - ADMIN_IDS=${ADMIN_IDS:-}
      # - LOG_LEVEL=${LOG_LEVEL:-INFO}
    # 健康检查
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import json; f=open('/app/config/config.json'); c=json.load(f); exit(0 if c.get('token') and c.get('admin_ids') else 1)",
        ]
      interval: 1m
      timeout: 10s
      retries: 3
